#!/bin/bash
echo -e "GET http://google.com HTTP/1.0\n\n" | nc google.com 80 > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "Online"
else
    echo "Offline , abos edak connect el Internet"
	exit
fi
workingDir=$(pwd)
sudo apt update
sudo apt-get install python3
sudo apt install python3-pip
pip3 --version
sudo apt install build-essential libssl-dev libffi-dev python3-dev
sudo apt-get install wget
sudo apt-get install git
sudo apt install python3-numpy python3-scipy python3-matplotlib
sudo apt install python3-opencv
pip3 install Pillow
sudo pip3 install --user --upgrade tensorflow
sudo pip3 install keras
sudo apt-get update
sudo apt-get install build-essential cmake pkg-config
sudo apt-get install python-opencv
sudo pip3 install opencv-python
sudo apt-get install python3-pyqt4
sudo apt-get install python-qt4 qt4-designer
sudo chmod 777 testTensorKeras
./testTensorKeras
python3 testOpenCV.py
python3 -c "import tensorflow as tf; tf.enable_eager_execution(); print(tf.reduce_sum(tf.random_normal([1000, 1000])))"
#cd /home/$USER/Downloads
read -p "Do you wanna install Pycharm , Enter y or n : " input
if  [ "$input" = "y" ] ;then
#file=pycharm
wget "https://download.jetbrains.com/python/pycharm-community-2018.3.2.tar.gz"
tar -xzf pycharm-community-2018.3.1.tar.gz
cd cd pycharm-community-2018.3.1/bin
./pycharm.sh
echo "Pycharm is installed successfully"
else 
	echo "Installation of pycharm aborted by user"
fi
echo "Ended successfully"

